project_name: insixio-uo-launcher

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build_noncgo
    main: ./app
    binary: insixio-launcher
    ldflags:
      - -s -w -X github.com/insixio/uo-launcher.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

snapshot:
  name_template: '{{ incpatch .Version }}-next'

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

git:
  prerelease_suffix: "-"
  ignore_tags:
    - nightly
    - dev

checksum:
  name_template: 'checksums.txt'

release:
  draft: true
  replace_existing_draft: true
  prerelease: auto

archives:
  - id: archive_noncgo
    builds: [build_noncgo]
    format: zip
    files:
      - LICENSE.md
      - CHANGELOG.md

changelog:
  sort: asc
  filters:
    exclude:
      - '^cfg:'
      - '^dev:'
      - '^test:'
